<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_magnificpopup_mfponly"
 *
 * Auto generated by Extension Builder 2014-12-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Magnific Popup only',
    'description' => 'Adds a checkbox to display an image only in Magnific Popup lightbox.',
    'category' => 'plugin',
    'author' => 'Jonathan Heilmann',
    'author_email' => 'mail@jonathan-heilmann.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.1.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-7.6.99',
            'news' => '3.2.0',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
